include(../RibiLibraries/WebApplication.pri)
include(../RibiLibraries/BigInteger.pri)
include(../RibiLibraries/BoostAll.pri)
include(../RibiLibraries/Wt.pri)
include(../RibiLibraries/GeneralConsole.pri)
include(../RibiLibraries/GeneralWeb.pri)

include(../RibiClasses/CppCanvas/CppCanvas.pri)
include(../RibiClasses/CppContainer/CppContainer.pri)
include(../RibiClasses/CppExercise/CppExercise.pri)
include(../RibiClasses/CppFuzzy_equal_to/CppFuzzy_equal_to.pri)
include(../RibiClasses/CppImageCanvas/CppImageCanvas.pri)
include(../RibiClasses/CppMultipleChoiceQuestion/CppMultipleChoiceQuestion.pri)
include(../RibiClasses/CppMultipleChoiceQuestionDialog/CppMultipleChoiceQuestionDialog.pri)
include(../RibiClasses/CppOpenQuestion/CppOpenQuestion.pri)
include(../RibiClasses/CppOpenQuestionDialog/CppOpenQuestionDialog.pri)
include(../RibiClasses/CppQuestion/CppQuestion.pri)
include(../RibiClasses/CppQuestionDialog/CppQuestionDialog.pri)
include(../RibiClasses/CppTribool/CppTribool.pri)
include(../RibiClasses/CppWtExercise/CppWtExercise.pri)
include(../RibiClasses/CppWtMultipleChoiceQuestionDialog/CppWtMultipleChoiceQuestionDialog.pri)
include(../RibiClasses/CppWtOpenQuestionDialog/CppWtOpenQuestionDialog.pri)
include(../RibiClasses/CppWtQuestionDialog/CppWtQuestionDialog.pri)

include(TestExerciseWebsite.pri)

SOURCES += wtmain.cpp
